# 02c Matrix Modeling
__Math 3080: Fundamentals of Data Science__

Reading: 
* Phillips, Chapter 3
* [3 Blue 1 Brown YouTube Series on Linear Algebra](https://www.youtube.com/playlist?list=PL0-GT3co4r2y2YErbmuJw2L5tW4Ew2O5B)
* Grus, Chapter 4

-----
__Outline__
* Matrix Multiplication
* Systems of Equations
* Using a Matrix to describe Data
* Solving for $\vec{\mathbf{x}}$
* Creating a Model
  * Weather info based on 3 observations of 3 variables: Temperature, Humidity, Pressure
  * Weather info based on 5 observations of 3 variables: Temperature, Humidity, Pressure
-----

In [7]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

This is a cumbersome command. Let's simplify it by implicitly importing the `inv` function.

In [9]:
from numpy.linalg import inv
inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])