# 04 Linear Algebra
__Math 3080: Fundamentals of Data Science__

Reading: 
* Phillips, Chapter 3
* [3 Blue 1 Brown YouTube Series on Linear Algebra](https://www.youtube.com/playlist?list=PL0-GT3co4r2y2YErbmuJw2L5tW4Ew2O5B)
* Grus, Chapter 4

-----
__Things to work on in this lecture__
* Display all vectors and matrices properly, according to math notation, not Python notation
* After they are shown properly, then we can show them in Python

__Outline__
* What is a vector
* Vector addition
* The (L2) Norm
* Vector scaling
* Basis vectors
* Dot Product
* The Matrix
* Matrix Multiplication

I have created a vector addition and vector scaling graph on Desmos.
* https://www.desmos.com/calculator/femuk0totw
-----

## Vectors
A vector is a series of numbers that combined describe the property of something. The most common example of a vector is a point on a graph. This is used a lot in physics to describe position, velocity, forces, electric and magnetic fields, and so on.

It is simply a collection of two or more points. For example, $\begin{bmatrix}5\\2\end{bmatrix}$ represents a vector that points from the origin to a point 5 units to the right and 2 units up.

In the physical world, we generally deal with points in 3 dimensions. Our minds cannot intuitively comprehend more dimensions than that. For example, if we consider an airport to be the origin, then the vector $\begin{bmatrix}75\\-10\\6\end{bmatrix}$ would indicate an airplane that is 75 miles to the East, 10 miles to the South, and 6 miles up vertically.


In [1]:
import numpy as np
x = np.array([75, -10, 6])


However, in the data world, a vector could contain 12 pieces of information to describe a particular object. This would then be depicted as a 12-dimensional vector. The following could be a list of items that describe the background of a student:
```python
# [height, weight, eye color, hair color, Grade in school, GPA, Housing, Pay Wage, Gender, Ethnicity, Marriage status, Religion]
person_1 = [71, 220, 'brown', 'black', 'Sophomore', 3.78, 'Off-campus', 12.70, 'M', 'Hispanic', 'Married', 'Catholic']
```

* *Note*: In a Python list or array, not all elements have to be the same type.

### Vector Addition
We can easily add two vectors together. Adding $A=\begin{bmatrix}5\\2\end{bmatrix}$ and $B=\begin{bmatrix}1\\6\end{bmatrix}$ would go 5 to the right plus an additional 1, the 2 up plus an additional 6. That is,
$$A+B=\begin{bmatrix}A_x\\A_y\end{bmatrix}+\begin{bmatrix}B_x\\B_y\end{bmatrix} = \begin{bmatrix}A_x+B_x\\A_y+B_y\end{bmatrix}$$
$$\begin{bmatrix}5\\2\end{bmatrix}+\begin{bmatrix}1\\6\end{bmatrix} = \begin{bmatrix}5+1\\2+6\end{bmatrix} = \begin{bmatrix}6\\8\end{bmatrix}$$

* Show Graphically on https://www.desmos.com/calculator/femuk0totw

In [20]:
A = np.array([5,2])
B = np.array([1,6])
A+B

array([6, 8])

In [39]:
# recall an indiviaul element of a vector
A[0]

5

In [40]:
A[1]

2

Note that this operation is commutative:
* Show Graphically

In [5]:
B+A

array([6, 8])

Subtraction also works:
$$\begin{bmatrix}5\\2\end{bmatrix} - \begin{bmatrix}1\\6\end{bmatrix} = \begin{bmatrix}5\\2\end{bmatrix} + \begin{bmatrix}-1\\-6\end{bmatrix} = \begin{bmatrix}5-1\\2-6\end{bmatrix} = \begin{bmatrix}4\\-4\end{bmatrix}$$

In [7]:
A-B

array([ 4, -4])

### The L2 Norm
A __Norm__ is a method of measuring the length of a vector. There are many ways to measure the length of a vector:
* L0 Norm (not really a norm, but some people use it that way)
* L1 Norm
* L2 Norm
* Infinity Norm

Since the L2 Norm is the one we will deal with the most in this class, we will only define this one.

The __L2 Norm__ is simply the length of the vector from tail to tip. Note how any vector can be written as a combination of vectors in $\vec{\mathbf{x}}$ and $\vec{\mathbf{y}}$:
$$\begin{bmatrix}5\\2\end{bmatrix} = \begin{bmatrix}5\\0\end{bmatrix} + \begin{bmatrix}0\\2\end{bmatrix}$$
This is a right triangle. So, the length of the vector can be found using the Pythagorean Theorem:
$$||\vec{\mathbf{x}}||_2 = \begin{vmatrix}A_x\\A_y\end{vmatrix} = \sqrt{A_x^2 + A_y^2}$$
$$||\vec{\mathbf{x}}||_2 = \begin{vmatrix}5\\2\end{vmatrix} = \sqrt{5^2 + 2^2} = \sqrt{25+4} = \sqrt{29} \approx 5.385$$
In 3 dimensions, we just add another term:
$$||\vec{\mathbf{x}}||_2 = \begin{vmatrix}A_x\\A_y\\A_z\end{vmatrix} = \sqrt{A_x^2 + A_y^2 + A_z^2}$$
$$||\vec{\mathbf{x}}||_2 = \begin{vmatrix}75\\-10\\6\end{vmatrix} = \sqrt{75^2 + (-10)^2 + 6^2} = \sqrt{5625+100+36} = \sqrt{5761} \approx 75.90$$
The result of the Pythagorean Theorem is known as the Euclidean distance, so this is also known as the __Euclidean Norm__.

In [34]:
x = np.array([75, -10, 6])

def twonorm(a):
    s = np.zeros(len(a))
    for i in range(len(a)):
        s[i] = a[i]**2
    return np.sqrt(sum(s))

twonorm(x)

75.9012516365837

* Take some time to describe
  * Functions
  * For loops
  * Range

In [31]:
from numpy.linalg import norm
norm(x)

75.9012516365837

In [32]:
norm(x, ord=2)

75.9012516365837

### Vector Multiplication
There are many ways to multiply vectors: Scalar multiplication, Dot product, Cross product, ...

#### Scalar Multiplication
A scalar is a value that increases or decreases the size of a vector but doesn't change the direction. It is simply a number multiplied by the vector:
$$10\begin{bmatrix}5\\2\end{bmatrix} = \begin{bmatrix}10*5\\10*2\end{bmatrix} = \begin{bmatrix}50\\20\end{bmatrix}$$

* Show Graphically on https://www.desmos.com/calculator/femuk0totw

In [22]:
x = np.array([5, 2])
10*x

array([50, 20])

#### Dot Product
The dot product is a multiplication method for vectors
$$\vec{x}=\begin{bmatrix}x_1\\x_2\end{bmatrix} \qquad \vec{y}=\begin{bmatrix}y_1\\y_2\end{bmatrix}$$
$$\vec{x} \cdot \vec{y} = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \cdot \begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = x_1y_1+x_2y_2$$
Another way to write this is using a transpose: $\vec{x}^T=\begin{bmatrix}x_1 & x_2\end{bmatrix}$
$$\vec{x} \cdot \vec{y} = \vec{x}^T\vec{y} = \begin{bmatrix} x_1 & x_2 \end{bmatrix} \begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = x_1y_1+x_2y_2$$

* Multiply first elements
* Go to the next elements (right in $\vec{x}$ and down in $\vec{y}$) and find their product
* Continue through all elements
* Add all products together

$$x_1 = \begin{bmatrix}1\\3\\4\end{bmatrix} \qquad x_2 = \begin{bmatrix}2\\4\\1\end{bmatrix}$$
$$x_1\cdot x_2 = x_1^T x_2 = \begin{bmatrix}1&3&4\end{bmatrix}\begin{bmatrix}2\\4\\1\end{bmatrix} = (1\cdot 2) + (3\cdot 4) + (4\cdot 1) = 2 + 12 + 4 = 18$$

In [35]:
x1 = np.array([1, 3, 4])
x2 = np.array([2, 4, 1])

def dotproduct(a,b):
    s = np.zeros(len(a))      # s = [0, 0, 0]
    for i in range(len(a)):
        s[i] = a[i] * b[i]    # s = [ax*bx , ay*by , az*bz] = [sx , sy , sz]
    return sum(s)             # sx + sy + sz

dotproduct(x1,x2)

18.0

In [36]:
def dotproduct(a,b):
    s = [a[i]*b[i] for i in range(len(a))]   # [ax*bx , ay*by , az*bz]
    return sum(s)                            #  ax*bx + ay*by + az*bz

dotproduct(x1,x2)

18

In [26]:
# NumPy built-in function
np.dot(x1, x2)

18

### Basis Vectors
A set of $k$ vectors is given: $X=\{x_1,x_2,...,x_k\}\in\mathbb{R}^d$. For example:
$$X=\{x_1,x_2\}\in\mathbb{R}^3 \qquad x_1=\begin{bmatrix}1\\3\\4\end{bmatrix} \qquad x_2=\begin{bmatrix}2\\4\\1\end{bmatrix}$$

A vector is __linearly dependent__ to $X$ if it can be written as a linear combination of the vectors in $X$.
$$z=\begin{bmatrix}-3\\-5\\2\end{bmatrix} = \begin{bmatrix}1\\3\\4\end{bmatrix} -\begin{bmatrix}4\\8\\2\end{bmatrix} = \begin{bmatrix}1\\3\\4\end{bmatrix} - 2\begin{bmatrix}2\\4\\1\end{bmatrix} = x_1-2x_2$$

In [9]:
x1 = np.array([1,3,4])
x2 = np.array([2,4,1])

x1 - 2*x2

array([-3, -5,  2])

On the other hand, a vector is __linearly independent__ if it __cannot__ be written as a linear combination of the vectors in $X$.
$$z=\begin{bmatrix}3\\7\\1\end{bmatrix} = \begin{bmatrix}1\\3\\4\end{bmatrix} -\begin{bmatrix}-2\\-4\\3\end{bmatrix} \ne c_1 x_1 + c_2 x_2$$

#### Span
The __span__ of a set of vectors is the set of __all__ vectors that can be written as a linear combination of vectors in $X$.

For example, there are two (linearly independent) vectors:
$$\hat{i}=\hat{x}=\begin{bmatrix}1\\0\end{bmatrix} \qquad \hat{j}=\hat{y}=\begin{bmatrix}0\\1\end{bmatrix}$$

Any 2D vector can be written as a linear combination of $\hat{i},\hat{j}$. Consider $\begin{bmatrix}7\\-9\end{bmatrix}$:

In [8]:
i_hat = np.array([1,0])
j_hat = np.array([0,1])

7*i_hat - 9*j_hat

array([ 7, -9])

Thus, $span(X) = \left\{z | z = c_x \hat{i} + c_y \hat{j}\right\}$ where $X = \begin{Bmatrix}\begin{bmatrix}1\\0\end{bmatrix}, \begin{bmatrix}0\\1\end{bmatrix}\end{Bmatrix}$

The vectors of $X$ are known as __basis vectors__ and can be used to depict any two-dimensional vector in the x-y coordinate system.

### The Matrix
If we put our two basis vectors together, we get a 2-dimensional vector, also known as a matrix:
$$\begin{bmatrix}\hat{i} & \hat{j}\end{bmatrix} = \begin{bmatrix}1 & 0 \\ 0 & 1 \end{bmatrix}$$
The left two numbers indicate the direction of one basis vector ($\hat{i}$) and the right two numbers indicate the direction of the other basis vector ($\hat{j}$). We can multiply this matrix with any vector and we get the original vector:
$$\begin{bmatrix}1 & 0 \\ 0 & 1 \end{bmatrix}\begin{bmatrix}5 \\ 2 \end{bmatrix}=5\begin{bmatrix}1 \\ 0 \end{bmatrix} + 2\begin{bmatrix}0 \\ 1 \end{bmatrix} = \begin{bmatrix}5+0\\0+2\end{bmatrix}=\begin{bmatrix}5\\2\end{bmatrix}$$
If instead we multiply our vector by a matrix with different basis vectors, then we pass our vector through a __linear transformation__ onto the new basis vector system.
$$\begin{bmatrix}3 & -1 \\ 1 & 5 \end{bmatrix}\begin{bmatrix}5 \\ 2 \end{bmatrix}=5\begin{bmatrix}3 \\ 1 \end{bmatrix} + 2\begin{bmatrix}-1 \\ 5 \end{bmatrix} = \begin{bmatrix}5(3) + 2(-1)\\5(1)+2(5)\end{bmatrix} = \begin{bmatrix}13 \\ 15 \end{bmatrix}$$

__*COME UP WITH BETTER NUMBERS FOR THIS TRANSFORMATION*__

* Look at the vector with basis vectors before and after the transformation

In [ ]:
L = np.array([[3,-1],
              [1,5]])

x = np.array([5,2])

In [42]:
# recall an element of a matrix
L[0,1]

-1

In [43]:
L[0][1]

-1

In [37]:
def multiplymatrix(A,x):
    s = np.zeros(len(x))
    for i in range(len(A[:,0])):
        for j in range(len(A[0])):
            s[i] += A[i,j]*x[j]
    return s

multiplymatrix(L,x)

array([13., 15.])

In [38]:
np.matmul(L,x)

array([13, 15])

### Matrix Multiplication

In [50]:
def multiply2matrices(A,B):
    s = np.zeros(B)
    return s

B = np.array([[1,2],
              [3,4]])

multiply2matrices(L,B)

TypeError: only integer scalar arrays can be converted to a scalar index